config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  devise_for :users
  
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  
  get 'home/about' => 'home#about'

  get 'search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length:{ maximum: 50 }

  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  
  has_many :book_comments, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def  followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    books_path
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
		@comment = current_user.book_comments.new(book_comment_params)
		@comment.book_id = @book.id
		@comment.save
		@book_comments = @book.book_comments
	end

	def destroy
		@comment = BookComment.find(params[:book_id])
		@book = @comment.book
		@book_comments = @book.book_comments
		@comment.destroy
	end
	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit,:update]

  def show
    @books = Book.new
  	@book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @book = Book.new
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id = current_user.id
    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
      render 'edit'
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def correct_user
    book = Book.find(params[:id])
    if book.user_id != current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: @book.id)
		favorite.save
	end

	def destroy
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: @book.id)
		favorite.destroy
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	follow = current_user.active_relationships.new(follower_id: (params[:user_id]))
  	follow.save
  	redirect_back(fallback_location: root_path)
  end

  def destroy
  	follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
  	follow.destroy
  	redirect_back(fallback_location: root_path)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  	@book = Book.new
  	if params[:model] == 'user'
	  	if params[:type] == 'perfect_match'
		  	@users = User.where(name: params[:term])
	    elsif params[:type] == 'part_match'
		  	@users = User.where('name like ?', "%#{params[:term]}%")
		elsif params[:type] == 'foward_match'
			@users = User.where('name like ?', "#{params[:term]}%")
		elsif params[:type] == 'back_match'
			@users = User.where('name like ?', "%#{params[:term]}")
		end
		render 'users/index'
	else params[:model] == 'book'
		if params[:type] == 'perfect_match'
			@books = Book.where(title: params[:term])
		elsif params[:type] == 'part_match'
			@books = Book.where('title like ?', "%#{params[:term]}%")
		elsif params[:type] == 'foward_match'
			@books = Book.where('title like ?', "#{params[:term]}%")
		elsif params[:type] == 'back_match'
			@books = Book.where('title like ?', "%#{params[:term]}")
		end
		render 'books/index'
	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comments.html.erb
<% book_comments.each do |book_comment| %>
	<li class="comment">
		<div class="comment-text">
			<div class="comment-author clearfix">
				<%= book_comment.user.name %>
				<span><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
			</div>
			<div class="comment-entry"> <%= book_comment.comment %></div>
		</div>
		<% if book_comment.user == current_user %>
		    <span><%= link_to "削除", book_book_comments_path(book_comment.id), method: :delete, remote: true %></span>
		<% end %>
	</li>
<% end %>

app/views/book_comments/_counts.html.erb
<span>コメント数：<%= book.book_comments.count %></span>

app/views/book_comments/_form.html.erb
<%= form_with(model: [@book, @book_comment]) do |f| %>
	<%= f.text_area :comment %>
	<%= f.submit "送信" %>
<% end %>

app/views/book_comments/create.js.erb
$('#counts_<%= @book.id %>').html ("<%= j(render partial: 'counts', locals: {book: @book}) %>");
$('#comments_<%= @book.id %>').html ("<%= j(render partial: 'comments', locals: {book_comments: @book_comments, book: @book}) %>");
$('#book_comment_comment').val('')

app/views/book_comments/destroy.js.erb
$("#counts_<%=@book.id %>").html ("<%= j(render partial: 'counts', locals: {book: @book}) %>");
$("#comments_<%=@book.id %>").html ("<%= j(render partial: 'comments', locals: {book_comments: @book_comments}) %>");

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
	<% if @book.errors.any? %>
		<h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
		<ul>
			<%= @book.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<% if @book.errors.any? %>
	<h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
	<ul>
		<%= @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
	<% end %>
</div>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<!-- 追加 -->
					<td id="favorites_bottons_<%= book.id %>">
						<%= render partial: 'favorites/favorite', locals: {book: book} %>
					</td>
					<!-- ここまで -->
					<td>
						コメント数：<%= book.book_comments.count %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book:@books %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<!-- いいね非同期通信 -->
					<td id="favorites_bottons_<%= @book.id %>">
						<%= render partial: 'favorites/favorite', locals: {book: @book} %>
					</td>
					<!-- いいね非同期通信 -->
					<!-- コメント数の非同期 -->
					<td id="counts_<%= @book.id %>">
						<%= render partial: 'book_comments/counts', locals: {book: @book} %>
					</td>
					<!-- コメント数の非同期 -->
					<% if @book.user == current_user %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<!-- コメント一覧の非同期 -->
			<ol id="comments_<%= @book.id %>">
					<%= render partial: 'book_comments/comments', locals: {book_comments: @book_comments, book: @book} %>
			</ol>
			<!-- コメント一覧の非同期	-->
			<!-- コメントフォームの非同期 -->
				<%= render partial: 'book_comments/form', locals: {comment: @comment, book: @book} %>
			<!-- コメントフォームの非同期 -->
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
	<div>
		<%= link_to book_favorites_path(book),method: :delete, remote: true do %>
		<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
		<%= book.favorites.count %>
		<% end %>
	</div>
<% else %>
	<div>
		<%=link_to book_favorites_path(book), method: :post, remote: true do %>
		<i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
		<%= book.favorites.count %>
		<% end %>
	</div>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_bottons_<%= @book.id %>' ).html ("<%= j(render partial: 'favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_bottons_<%= @book.id %>').html("<%= j(render partial: 'favorite', locals: {book: @book}) %>");

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th><%= link_to user.active_relationships.count, follows_user_path(user.id) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to user.passive_relationships.count, followers_user_path(user.id) %></th>
		</tr>
</table>

<div class="row">
	<% if current_user != user %>
	  <% if user.followed_by?(current_user) %>
	    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
	  <% else %>
	    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
	  <% end %>
	<% else %>
	  <%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<div class="row">
	<h2>Follow Users</h2>
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		  <% @users.each do |user| %>
		    <tr>
		    	<td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
		    	<td><%= user.name %></td>
		    	<td>フォロー数：<%= user.active_relationships.count %></td>
		    	<td>フォロワー数：<%= user.passive_relationships.count %></td>
		    	<td>
		    		<% if user.followed_by?(current_user) %>
		    		  <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
		    		<% else %>
		    		  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
		    		<% end %>
		    	</td>
		    	<td><%= link_to "show", user_path(user.id) %></td>
		    </tr>
		    <% end %>
		<tbody>
		</tbody>
	</table>
</div>

app/views/users/follows.html.erb
<div class="row">
	<h2>Follow Users</h2>
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		  <% @users.each do |user| %>
		    <tr>
		    	<td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
		    	<td><%= user.name %></td>
		    	<td>フォロー数：<%= user.active_relationships.count %></td>
		    	<td>フォロワー数：<%= user.passive_relationships.count %></td>
		    	<td>
		    		<% if user.followed_by?(current_user) %>
		    		  <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
		    		<% else %>
		    		  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
		    		<% end %>
		    	</td>
		    	<td><%= link_to "show", user_path(user.id) %></td>
		    </tr>
		    <% end %>
		<tbody>
		</tbody>
	</table>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">

		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td>フォロー数：<%= user.active_relationships.count %></td>
					<td>フォロワー数：<%= user.passive_relationships.count %></td>
					<td>
						<% if current_user != user %>
						  <% if user.followed_by?(current_user) %>
						    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
						  <% else %>
						    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
						  <% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>コメント数：<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>